apiVersion: v1
kind: Service
metadata:
  name: my-kafka
spec:
  ports:
    - port: 9092
      name: plaintext
      targetPort: 9092
  selector:
    app: my-kafka
  clusterIP: None # Headless Service

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-kafka
spec:
  selector:
    matchLabels:
      app: my-kafka
  serviceName: my-kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: my-kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.7.0 # Apache 공식 이미지 (확실히 존재함!)
          ports:
            - containerPort: 9092
          env:
            # KRaft 모드 설정 (개발용 단일 노드)
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://my-kafka-0.my-kafka.default.svc.cluster.local:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@my-kafka-0.my-kafka.default.svc.cluster.local:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"