apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: omni-order-project

# ===========================
# 1. 기본 설정 (Local)
# ===========================
build:
  artifacts:
    - image: creamdocker/order-service
      context: ./Order-Service
      docker: { dockerfile: Dockerfile }
    - image: creamdocker/product-service
      context: ./Product-Service
      docker: { dockerfile: Dockerfile }
    - image: creamdocker/message-service
      context: ./message-service
      docker: { dockerfile: Dockerfile }

deploy:
  # [1] 일반 YAML 파일 배포 (Eureka, DB, Redis 등)
  kubectl:
    manifests:
      - ./k8s/eureka-deployment.yaml
      - ./k8s/database-deployment.yaml # (로컬 DB도 필요하다면 추가)
      - ./k8s/redis-deployment.yaml    # (로컬 Redis도 필요하다면 추가)
      - ./k8s/ingress.yaml

  # [2] Helm 차트 배포 (우리가 만든 서비스들)
  helm:
    releases:
      - name: order-service
        chartPath: ./k8s/order-chart
        valuesFiles: [./k8s/order-chart/values.yaml]
        artifactOverrides:
          image: creamdocker/order-service
        skipBuildDependencies: true

      - name: product-service
        chartPath: ./k8s/product-chart
        valuesFiles: [./k8s/product-chart/values.yaml]
        artifactOverrides:
          image: creamdocker/product-service
        skipBuildDependencies: true

      - name: message-service
        chartPath: ./k8s/message-chart
        valuesFiles: [./k8s/message-chart/values.yaml]
        artifactOverrides:
          image: creamdocker/message-service
        skipBuildDependencies: true
# ===========================
# 2. 프로필 설정 (AWS)
# ===========================
profiles:
  - name: prod
    build:
      artifacts:
        # AWS ECR 주소로 매핑 (본인 계정 ID 입력 필수)
        - image: 414813661603.dkr.ecr.ap-northeast-2.amazonaws.com/order-service
          context: ./Order-Service
          docker: { dockerfile: Dockerfile }
        - image: 414813661603.dkr.ecr.ap-northeast-2.amazonaws.com/product-service
          context: ./Product-Service
          docker: { dockerfile: Dockerfile }
        - image: 414813661603.dkr.ecr.ap-northeast-2.amazonaws.com/message-service
          context: ./message-service
          docker: { dockerfile: Dockerfile }

    deploy:
      helm:
        releases:
          - name: order-service
            chartPath: ./k8s/charts/order-service
            # [중요] prod용 파일 사용
            valuesFiles: [./k8s/order-chart/values.yaml]
            # values.yaml의 'image' 키를 ECR 주소 이미지로 덮어쓰기
            artifactOverrides:
              image: 414813661603.dkr.ecr.ap-northeast-2.amazonaws.com/order-service

          - name: product-service
            chartPath: ./k8s/charts/product-service
            valuesFiles: [./k8s/product-chart/values.yaml]
            artifactOverrides:
              image: 414813661603.dkr.ecr.ap-northeast-2.amazonaws.com/product-service

          - name: message-service
            chartPath: ./k8s/charts/message-service
            valuesFiles: [./k8s/message-chart/values.yaml]
            artifactOverrides:
              image: 414813661603.dkr.ecr.ap-northeast-2.amazonaws.com/message-service