-- 주문 테이블 생성 (테이블 명을 orders로 지정)

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    total_price INTEGER,
    order_status VARCHAR(50),
    created_at TIMESTAMP DEFAULT NOW()
);

-- (참고) 만약 외래키(FK)를 걸고 싶다면 나중에 V2__add_fk.sql 같은 파일을 만들어서 추가하면 됩니다.