# application.yml (Order Service)

# --- [ Spring 설정 블록: 모든 spring 관련 설정을 여기에 넣습니다. ] ---
spring:
  # 1. Datasource 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE # DB 접속 정보 확인
    username: omni
    password: omni

  # 2. JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # 3. Application Name 설정
  application:
    name: order-service

  # 4. Redis 설정 (spring 하위에 data:redis 구조로 배치)
  data:
    redis:
      host: localhost
      port: 6379

# --- [ 최상위 설정 블록: spring 블록과 동일 레벨 ] ---

server:
  port: 8081 # Order Service 포트

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/