-- PostgreSQL 문법으로 작성된 테이블 생성문

CREATE TABLE products (
    -- BIGINT + GENERATED ... IDENTITY가 자바의 Long + @GeneratedValue(IDENTITY)와 짝꿍입니다.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    stock INTEGER NOT NULL,
    price INTEGER
);

-- 초기 데이터도 여기서 넣으면 관리하기 편합니다 (선택 사항)
INSERT INTO products (name, stock, price) VALUES ('맥북 프로 16인치', 10, 3500000);
INSERT INTO products (name, stock, price) VALUES ('아이폰 15', 100, 1200000);
INSERT INTO products (name, stock, price) VALUES ('에어팟 맥스', 50, 700000);